### ISSUE TITLE
Write report and slides 

### ISSUE THREAD

**Issue by InesVATI** [balthazarneveu/sprectral_graph_convolutions#16]
- [x] decide plan 
- [x] write slide template
- [x] write introduction, context and solution (limitations of the proposed solution)

**Comment by balthazarneveu** [comment]
https://github.com/balthazarneveu/spectral_graph_convolutions/blob/main/report/87_Ines_VATI_Manal_AKHANNOUSS_Balthazar_NEVEU.pdf :rocket:
