### ISSUE TITLE
Studying ABIDE dataset

### ISSUE THREAD

**Issue by InesVATI** [balthazarneveu/sprectral_graph_convolutions#4]
Get familiar with the ABIDE dataset : 
- size of the dataset
- is preprocessing time-consuming and necessary ?
- extract feature vector ?

**Comment by InesVATI** [comment]
## Data 
I realised that the data that are used in the article (for ABIDE) are not images but time series.  Indeed, as you've mentionned in our last meeting, fMRI are very large files. It is not optimal to work locally with this type of data with limited memory capacity. See the Readme of ABIDE_dataset folder for more details.

## How can you use the code ?
I add two python files, largely inspired by the github of the authors but modified/reorganised so that it is easier to understand quickly I think : 
- download_preprocess : 
         - enables you to download as many preprocessed data as you want in a local folder of your choice (outside our github folder)
         - For 400 subjects, it took nearly 10min to download and compute full connectivity matrices and 132 Mo in size.

- ABIDE_graph : *in progress* 
       - enables to compute features by computing the connectivity measure on rs-fMRI (relaxing-state) time series and reducing their dimension.
       - to compute the weight of the edges and construct the graph (not done yet)

## Important remarks : 
I agree that it is useless to reproduce the result of the article. So, we can still use this dataset to try other methods and/or test the proposed method with other features.

**Comment by balthazarneveu** [comment]
[visualize_data.ipynb](https://github.com/balthazarneveu/sprectral_graph_convolutions/blob/4-studying-abide-dataset/ABIDE_dataset/visualize_data.ipynb)
