### ISSUE TITLE
Spectral graph theory for convolutions 

### ISSUE THREAD

**Issue by InesVATI** [balthazarneveu/sprectral_graph_convolutions#5]
What to do?
- a latex note on the theory
OPTIONAL but strongly recommended to avoid mistakes & make sure the equations are correctly written:
- a simple python code applied to a  graph mimicking a regular grid (something like 8 neighbors connectivity) to make sure that you actually mimick a standard convolution.

**Comment by balthazarneveu** [comment]
Must read [GNN distill article](https://distill.pub/2021/understanding-gnns/#spectral)
[Bart Wronsky's](https://bartwronski.com/2022/05/26/removing-blur-from-images-deconvolution-and-using-optimized-simple-filters/)  note on how a circulant matrix (which corresponds to a convolution) "magically"  decomposes into a Fourier basis when you do a SVD...

**Comment by balthazarneveu** [comment]
In the following code from [ALTEGRAD Lab on graphs - spectral clustering](https://github.com/balthazarneveu/MVA23_ALTEGRAD/blob/lab/lab2/Lab2/code/code_lab_community_detection.py#L1-L91) , we used Network X, computed the Laplacian spare matrix (not normalized the same way as in the paper), perform SVD ... (and then clustered using K - nearest neighbors which is not what we'd like to do here.)
